'use client';
import {useEffect,useState} from 'react';
import {Bell,BellRing} from 'lucide-react';
import {toast} from 'sonner';
function bytes(s){const pad='='.repeat((4-s.length%4)%4),raw=atob((s+pad).replace(/-/g,'+').replace(/_/g,'/'));return Uint8Array.from([...raw].map(c=>c.charCodeAt(0)))}
export default function AegisNotifications({token}){
 const [enabled,setEnabled]=useState(false),[busy,setBusy]=useState(false),[status,setStatus]=useState('');
 const supported=typeof window!=='undefined'&&'serviceWorker'in navigator&&'PushManager'in window&&'Notification'in window;
 useEffect(()=>{let active=true;(async()=>{if(!supported){setStatus('Push unavailable in this browser');return}if(Notification.permission==='denied'){setStatus('Notifications blocked in browser settings');return}try{const reg=await navigator.serviceWorker.getRegistration('/');const sub=await reg?.pushManager?.getSubscription();if(!sub){if(active)setStatus('Alerts not enabled on this device');return}const res=await fetch('/api/admin/aegis/notifications',{method:'POST',headers:{Authorization:'Bearer '+token,'Content-Type':'application/json'},body:JSON.stringify({subscription:sub.toJSON()})});if(!res.ok)throw new Error('Subscription not registered on server');if(active){setEnabled(true);setStatus('Device subscription registered')}}catch(e){if(active){setEnabled(false);setStatus(e.message||'Notification check failed')}}})();return()=>{active=false}},[supported,token]);
 const enable=async()=>{setBusy(true);try{if(!supported)throw new Error('Push unavailable in this browser');if(await Notification.requestPermission()!=='granted')throw new Error('Notifications permission not granted');const cfgRes=await fetch('/api/admin/aegis/notifications',{headers:{Authorization:'Bearer '+token},cache:'no-store'});if(!cfgRes.ok)throw new Error('Cannot read notification configuration');const cfg=await cfgRes.json();if(!cfg.configured||!cfg.diagnostic?.privateKeyPresent||!cfg.diagnostic?.alertSecretPresent)throw new Error('Push delivery is not fully configured on the server');const reg=await navigator.serviceWorker.register('/aegis-sw.js',{scope:'/'});await navigator.serviceWorker.ready;let sub=await reg.pushManager.getSubscription();if(!sub)sub=await reg.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:bytes(cfg.publicKey)});const r=await fetch('/api/admin/aegis/notifications',{method:'POST',headers:{Authorization:'Bearer '+token,'Content-Type':'application/json'},body:JSON.stringify({subscription:sub.toJSON()})});if(!r.ok)throw new Error('Could not register this device');setEnabled(true);setStatus('Device subscription registered');toast.success('Aegis device registered for alerts')}catch(e){setEnabled(false);setStatus(e.message||'Could not enable alerts');toast.error(e.message||'Could not enable alerts')}finally{setBusy(false)}};
 const test=async()=>{setBusy(true);try{const r=await fetch('/api/admin/aegis/notifications/test',{method:'POST',headers:{Authorization:'Bearer '+token}});const d=await r.json();if(!r.ok||!d.sent)throw new Error(d.error||('No push delivered. Registered devices: '+(d.subscriptions??0)+', failed: '+(d.failed??0)));toast.success('Test push sent to '+d.sent+' device(s)');setStatus('Test push accepted by '+d.sent+' push service(s); check your device')}catch(e){setStatus(e.message||'Test failed');toast.error(e.message||'Test failed')}finally{setBusy(false)}};return <div className="flex flex-col gap-1"><button onClick={enable} disabled={busy||enabled||!supported} className="flex items-center gap-2 rounded-xl border border-[#D4AF37]/25 bg-[#D4AF37]/5 px-3 py-2 text-[11px] text-[#efbd63] disabled:opacity-60">{enabled?<BellRing className="w-4 h-4"/>:<Bell className="w-4 h-4"/>}{enabled?'Aegis Device Registered':busy?'Enabling…':'Enable Aegis Alerts'}</button><button type="button" onClick={test} disabled={busy||!enabled} className="rounded-xl border border-[#D4AF37]/25 px-3 py-2 text-[11px] text-[#efbd63] disabled:opacity-50">Send Test Notification</button><span className="text-[10px] text-gray-500" role="status">{status}</span></div>
}