'use client';
import {useEffect,useMemo,useRef,useState} from 'react';
import {Home,Users,Boxes,BarChart3,Settings,RefreshCw,ChevronLeft,ChevronRight,Save,ScanFace,ShieldCheck,Activity,CheckCircle2,Clock3,HeartPulse} from 'lucide-react';
import {toast} from 'sonner';

const NAMES=['Aegis','Scout','Brew','Steward','Ledger','Muse'];
const META={Aegis:{role:'Overseer',duties:['Supervise the AI team','Coordinate work and handoffs','Surface incidents and owner decisions']},Scout:{role:'Lead Gen & Marketing',duties:['Find and qualify business leads','Research local opportunities','Hand qualified leads to Brew']},Brew:{role:'Sales & Relationships',duties:['Handle lead conversations','Arrange samples and meetings','Move approved sales toward orders']},Steward:{role:'Inventory & Operations',duties:['Track stock and reserve','Coordinate purchases and fulfilment','Verify operational order readiness']},Ledger:{role:'Client Support',duties:['Verify payment events independently','Handle invoices and post-purchase care','Track feedback and customer follow-up']},Muse:{role:'Brand & Ideation',duties:['Support brand and content ideation','Stay available on retainer','Protect Estate Tea brand direction']}};
const PORTRAITS={Aegis:'/agents/sm_aegis.jpg',Scout:'/agents/sm_scout.jpg',Brew:'/agents/sm_brew.jpg',Steward:'/agents/sm_steward.jpg',Ledger:'/agents/sm_ledger.jpg',Muse:'/agents/sm_muse.jpg'};
const CONTROL_COPY=[['Owner approval gates','Consequential customer-facing actions stay behind owner approval where configured.'],['Agent availability','See whether each agent is online, paused, connecting or on retainer.'],['Work visibility','Review current task, daily progress, recent work and reported health from one place.'],['Aegis oversight','Aegis remains the supervisor and owner conversation layer across the app.'],['Inventory authority','Owner-entered physical stock remains the shared operational stock reference.'],['Customer sends','Customer communication follows the existing approval and agent workflow rather than bypassing it.']];

export default function AIOpsSwipePanel({token,faceIDReady=false,faceIDBusy=false,onSetupFaceID}){
 const [section,setSection]=useState('home'),[data,setData]=useState(null),[sales,setSales]=useState(null),[inventory,setInventory]=useState(null),[loading,setLoading]=useState(false),[index,setIndex]=useState(0),[stock,setStock]=useState(''),[saving,setSaving]=useState(false);
 const rail=useRef(null);const headers={'Content-Type':'application/json',Authorization:`Bearer ${token}`};
 const refresh=async()=>{setLoading(true);await Promise.allSettled([['/api/admin/aegis/dashboard',setData],['/api/admin/sales',setSales],['/api/admin/inventory',setInventory]].map(async([url,setter])=>{const r=await fetch(url,{headers,cache:'no-store'});if(r.ok)setter(await r.json())}));setLoading(false)};
 useEffect(()=>{refresh()},[token]);useEffect(()=>{const v=inventory?.physical_kg??inventory?.inventory?.physical_kg;if(v!=null)setStock(String(v))},[inventory]);
 const snap=data?.snapshot||{},raw=snap.agents||[],activity=data?.recent_activity||[],inv=inventory||snap.inventory||{};
 const agents=useMemo(()=>NAMES.map(name=>raw.find(a=>a.agent===name)||{agent:name,status:name==='Muse'?'standby':'connecting',enabled:true}),[raw]);
 const status=a=>a.enabled===false?'Paused':a.agent==='Muse'?'On Retainer':['online','active','running','healthy'].includes(String(a.status).toLowerCase())?'Online':a.status==='connecting'?'Connecting…':(a.status||'Unknown');
 const health=a=>a.health||a.health_status||(['online','active','running','healthy'].includes(String(a.status).toLowerCase())?'Healthy':a.enabled===false?'Paused':'Checking');
 const task=a=>a.current_task||a.task||(a.agent==='Aegis'?'Monitoring Estate Tea AI':a.agent==='Muse'?'Ready when needed':'No active task');
 const agentActivity=a=>activity.filter(x=>String(x.agent||x.source||x.metadata?.target_agent||'').toLowerCase()===a.agent.toLowerCase()).slice(0,6);
 const progress=a=>{const done=Number(a.completed_today??a.completed??a.progress_completed),total=Number(a.daily_total??a.total_today??a.progress_total);return Number.isFinite(done)&&Number.isFinite(total)&&total>0?{done,total,pct:Math.min(100,Math.round(done/total*100))}:null};
 const go=i=>{const n=Math.max(0,Math.min(agents.length-1,i));setIndex(n);rail.current?.children?.[n]?.scrollIntoView({behavior:'smooth',inline:'center',block:'nearest'})};
 const onScroll=()=>{const el=rail.current;if(!el)return;const center=el.scrollLeft+el.clientWidth/2;let best=0,dist=Infinity;[...el.children].forEach((c,i)=>{const d=Math.abs(c.offsetLeft+c.offsetWidth/2-center);if(d<dist){dist=d;best=i}});setIndex(best)};
 const saveStock=async()=>{const physical_kg=Number(stock);if(!Number.isFinite(physical_kg)||physical_kg<0)return toast.error('Enter a valid stock amount');setSaving(true);try{const r=await fetch('/api/admin/inventory',{method:'PUT',headers,body:JSON.stringify({physical_kg})});const b=await r.json();if(!r.ok)throw new Error(b.error||b.detail||'Inventory update failed');setInventory(b);toast.success(`Inventory set to ${physical_kg} kg`)}catch(e){toast.error(e.message)}finally{setSaving(false)}};
 const nav=[[Home,'home','Home'],[Users,'agents','Agents'],[Boxes,'inventory','Inventory'],[BarChart3,'reports','Reports'],[Settings,'settings','Settings']];
 return <div className="min-h-[70vh] grid lg:grid-cols-[190px_1fr] gap-6 text-white"><aside className="lg:sticky lg:top-20 lg:self-start flex lg:flex-col gap-2 overflow-x-auto py-1">{nav.map(([I,id,label])=><button key={id} onClick={()=>setSection(id)} className={`flex items-center gap-3 rounded-xl px-4 py-3 text-sm whitespace-nowrap border ${section===id?'border-[#d7a84b]/35 bg-[#d7a84b]/10 text-[#efbd63]':'border-transparent text-gray-500'}`}><I className="w-4 h-4"/>{label}</button>)}</aside><main className="min-w-0 space-y-5"><Header loading={loading} refresh={refresh}/>
 {section==='home'&&<><div className="flex items-end justify-between gap-4"><div><p className="text-[10px] uppercase tracking-[.24em] text-gray-600">Live team deck</p><h2 className="text-xl text-[#efbd63] mt-1">Swipe left or right</h2><p className="text-xs text-gray-500 mt-1">One agent at a time — their work, duties, progress and health.</p></div><div className="flex gap-2"><button onClick={()=>go(index-1)} disabled={index===0} className="p-2 rounded-full border border-white/10 disabled:opacity-20"><ChevronLeft className="w-4 h-4"/></button><button onClick={()=>go(index+1)} disabled={index===agents.length-1} className="p-2 rounded-full border border-white/10 disabled:opacity-20"><ChevronRight className="w-4 h-4"/></button></div></div><div ref={rail} onScroll={onScroll} className="flex gap-4 overflow-x-auto snap-x snap-mandatory overscroll-x-contain pb-3 -mx-4 px-[8vw] sm:px-[12vw] [scrollbar-width:none] [&::-webkit-scrollbar]:hidden" style={{WebkitOverflowScrolling:'touch',touchAction:'pan-x pan-y'}}>{agents.map((a,i)=><AgentSlide key={a.agent} agent={a} active={i===index} status={status(a)} health={health(a)} task={task(a)} progress={progress(a)} activity={agentActivity(a)}/>)}</div><div className="flex justify-center gap-1.5">{agents.map((a,i)=><button key={a.agent} aria-label={`Show ${a.agent}`} onClick={()=>go(i)} className={`h-1.5 rounded-full transition-all ${i===index?'w-7 bg-[#efbd63]':'w-1.5 bg-white/20'}`}/>)}</div><div className="grid grid-cols-2 lg:grid-cols-4 gap-3"><Metric label="Website orders" value={sales?.website?.summary?.orders||0}/><Metric label="AI sales orders" value={sales?.ai_sales?.summary?.orders||0}/><Metric label="Open incidents" value={snap.attention?.open_incidents||0}/><Metric label="Sellable kg" value={inv.sellable_kg??'—'}/></div></>}
 {section==='agents'&&<AgentsOverview agents={agents} status={status} health={health} task={task} progress={progress} activity={agentActivity}/>} 
 {section==='inventory'&&<div className="rounded-2xl border border-white/10 bg-[#0c0c0c] p-5"><h2 className="text-xl text-[#efbd63]">Inventory</h2><p className="text-xs text-gray-500 mt-1">Shared live stock for Steward, Brew and Aegis.</p><div className="mt-5 flex gap-2"><input value={stock} onChange={e=>setStock(e.target.value)} inputMode="decimal" className="min-w-0 flex-1 rounded-xl bg-white/5 border border-white/10 px-4 py-3 text-white" placeholder="Physical stock kg"/><button onClick={saveStock} disabled={saving} className="rounded-xl bg-[#efbd63] text-black px-4 flex items-center gap-2 text-xs"><Save className="w-4 h-4"/>{saving?'Saving…':'Save'}</button></div></div>}
 {section==='reports'&&<div className="grid sm:grid-cols-3 gap-3"><Metric label="Website orders" value={sales?.website?.summary?.orders||0}/><Metric label="AI sales orders" value={sales?.ai_sales?.summary?.orders||0}/><Metric label="Sellable kg" value={inv.sellable_kg??'—'}/></div>}
 {section==='settings'&&<div className="rounded-2xl border border-white/10 bg-[#0c0c0c] p-5"><div className="flex gap-3"><ScanFace className="w-5 h-5 text-[#efbd63]"/><div><h3>Face ID unlock</h3><p className="text-xs text-gray-500 mt-1">{faceIDReady?'Face ID sign-in is registered on the owner app.':'Face ID sign-in has not been set up on this device.'}</p><button onClick={onSetupFaceID} disabled={faceIDBusy||!onSetupFaceID} className="mt-4 rounded-xl border border-[#d7a84b]/30 bg-[#d7a84b]/10 px-4 py-2.5 text-xs text-[#efbd63]">{faceIDBusy?'Setting up…':faceIDReady?'Create new Face ID sign-in':'Set up Face ID'}</button></div></div></div>}
 </main></div>}
function Header({loading,refresh}){const h=new Date().getHours(),g=h<12?'Good morning':h<17?'Good afternoon':'Good evening';return <div className="flex justify-between gap-4"><div><p className="text-xs text-gray-600">{new Date().toLocaleDateString('en-IN',{weekday:'short',day:'numeric',month:'short',year:'numeric'})}</p><h1 className="mt-1 text-3xl sm:text-4xl font-light">{g}, <span className="text-[#efbd63]">Jaden.</span></h1><p className="mt-1 text-sm text-gray-500">Here’s your team at work.</p></div><button onClick={refresh} className="self-start p-2 text-gray-600"><RefreshCw className={`w-4 h-4 ${loading?'animate-spin':''}`}/></button></div>}
function AgentSlide({agent,active,status,health,task,progress,activity}){return <article className={`snap-center snap-always shrink-0 w-[82vw] sm:w-[520px] lg:w-[620px] rounded-[30px] overflow-hidden border bg-[#0c0c0c] transition-all duration-300 ${active?'border-[#efbd63]/55 scale-100 opacity-100 shadow-[0_22px_80px_rgba(0,0,0,.55)]':'border-white/10 scale-[.94] opacity-55'}`}><div className="relative h-60 sm:h-72"><img src={PORTRAITS[agent.agent]} alt={`${agent.agent} portrait`} className="w-full h-full object-cover"/><div className="absolute inset-0 bg-gradient-to-t from-[#0c0c0c] via-black/5 to-transparent"/><div className="absolute bottom-5 left-5"><p className="text-4xl text-[#efbd63]">{agent.agent}</p><p className="text-sm text-gray-300">{META[agent.agent].role}</p></div><span className="absolute top-4 right-4 rounded-full bg-black/70 backdrop-blur px-3 py-1.5 text-[11px] text-green-300">{status}</span></div><div className="p-5 space-y-5"><div className="grid grid-cols-2 gap-3"><Mini icon={HeartPulse} label="Health" value={health}/><Mini icon={Activity} label="State" value={status}/></div><section><p className="eyebrow">Today’s task</p><p className="mt-2 text-sm text-gray-200 leading-relaxed">{task}</p></section><section><p className="eyebrow">Core duties</p><div className="mt-2 grid gap-2">{META[agent.agent].duties.map(d=><p key={d} className="flex gap-2 text-xs text-gray-400"><CheckCircle2 className="w-3.5 h-3.5 text-[#efbd63] shrink-0 mt-0.5"/>{d}</p>)}</div></section>{progress?<section><div className="flex justify-between text-xs"><span className="text-gray-500">Daily progress</span><span className="text-[#efbd63]">{progress.done}/{progress.total} · {progress.pct}%</span></div><div className="h-1.5 bg-white/10 rounded-full mt-2 overflow-hidden"><div className="h-full bg-[#efbd63] rounded-full" style={{width:`${progress.pct}%`}}/></div></section>:<section><p className="eyebrow">Daily progress</p><p className="mt-2 text-xs text-gray-500">No measurable daily total has been reported yet.</p></section>}<section><p className="eyebrow">Work completed / recent activity</p><div className="mt-2 space-y-2">{activity.length?activity.map((x,i)=><p key={i} className="text-xs text-gray-400 border-b border-white/5 pb-2">{x.summary||x.event_type||'Activity recorded'}</p>):<p className="text-xs text-gray-600">No recent activity reported.</p>}</div></section></div></article>}
function AgentsOverview({agents,status,health,task,progress,activity}){return <div className="space-y-5"><div><p className="text-[10px] uppercase tracking-[.24em] text-gray-600">Team directory</p><h2 className="text-xl text-[#efbd63] mt-1">All agents</h2><p className="text-xs text-gray-500 mt-1">Every agent together. The Home screen is the swipe deck.</p></div><div className="grid sm:grid-cols-2 xl:grid-cols-3 gap-4">{agents.map(a=>{const p=progress(a),recent=activity(a);return <article key={a.agent} className="rounded-2xl overflow-hidden border border-white/10 bg-[#0c0c0c]"><div className="h-36 relative"><img src={PORTRAITS[a.agent]} alt={`${a.agent} portrait`} className="w-full h-full object-cover"/><div className="absolute inset-0 bg-gradient-to-t from-[#0c0c0c] to-transparent"/><div className="absolute bottom-3 left-4"><h3 className="text-xl text-[#efbd63]">{a.agent}</h3><p className="text-[11px] text-gray-300">{META[a.agent].role}</p></div></div><div className="p-4"><div className="flex justify-between text-[11px]"><span className="text-green-300">{status(a)}</span><span className="text-gray-500">Health: {health(a)}</span></div><p className="mt-3 text-xs text-gray-300 min-h-8">{task(a)}</p>{p&&<p className="mt-3 text-[11px] text-[#efbd63]">Today {p.done}/{p.total} · {p.pct}%</p>}<p className="mt-3 text-[11px] text-gray-600">{recent.length?`${recent.length} recent activity item${recent.length===1?'':'s'}`:'No recent activity'}</p></div></article>})}</div><AgentControls agents={agents} status={status}/></div>}
function AgentControls({agents,status}){return <section className="rounded-[26px] border border-[#efbd63]/20 bg-[#0c0c0c] p-5"><div className="flex items-start gap-3"><ShieldCheck className="w-5 h-5 text-[#efbd63] mt-0.5"/><div><p className="text-[10px] uppercase tracking-[.24em] text-gray-600">Owner controls</p><h3 className="text-xl text-[#efbd63] mt-1">Agent control centre</h3><p className="text-xs text-gray-500 mt-1">Your operational controls and safeguards in one place.</p></div></div><div className="grid sm:grid-cols-2 gap-3 mt-5">{CONTROL_COPY.map(([title,copy])=><div key={title} className="rounded-xl border border-white/10 bg-white/[.025] p-4"><p className="text-sm text-white">{title}</p><p className="text-xs text-gray-500 mt-1 leading-relaxed">{copy}</p></div>)}</div><div className="mt-5"><p className="eyebrow">Live agent states</p><div className="grid grid-cols-2 sm:grid-cols-3 gap-2 mt-2">{agents.map(a=><div key={a.agent} className="rounded-xl border border-white/10 px-3 py-2"><p className="text-xs text-gray-300">{a.agent}</p><p className="text-[10px] text-[#efbd63] mt-1">{status(a)}</p></div>)}</div></div></section>}
function Mini({icon:Icon,label,value}){return <div className="rounded-xl border border-white/10 bg-white/[.025] p-3"><Icon className="w-4 h-4 text-[#efbd63]"/><p className="text-[9px] uppercase tracking-wider text-gray-600 mt-2">{label}</p><p className="text-xs text-gray-300 mt-1">{value}</p></div>}
function Metric({label,value}){return <div className="rounded-2xl border border-white/10 bg-[#0c0c0c] p-4"><p className="text-[10px] uppercase tracking-wider text-gray-600">{label}</p><p className="text-2xl text-[#efbd63] mt-2">{value}</p></div>}
