import {useEffect,useMemo,useState} from 'react';
import {Bot,Send,RefreshCw,AlertTriangle,CheckCircle2,Clock3,PackageOpen,Globe2,BriefcaseBusiness,Boxes,ChevronRight,X,Home,Users,BarChart3,Settings,MessageCircle} from 'lucide-react';
import {toast} from 'sonner';
const META={Aegis:['Overseer','AE'],Scout:['Lead Generation + Marketing','SC'],Brew:['Sales + Relationships','BR'],Steward:['Inventory + Operations','ST'],Ledger:['Payments + Client Care','LE'],Muse:['Brand + Content','MU']};
export default function AIOpsPanel({token}){
 const [data,setData]=useState(null),[sales,setSales]=useState(null),[inventory,setInventory]=useState(null),[approvals,setApprovals]=useState({count:0,items:[]}),[loading,setLoading]=useState(true),[message,setMessage]=useState(''),[sending,setSending]=useState(false),[lastCommand,setLastCommand]=useState(null),[reviewing,setReviewing]=useState(false),[busyApproval,setBusyApproval]=useState(null),[section,setSection]=useState('home'),[report,setReport]=useState('website'),[selected,setSelected]=useState('Aegis'),[detailTab,setDetailTab]=useState('activity'),[stockInput,setStockInput]=useState(''),[savingStock,setSavingStock]=useState(false);
 const headers={'Content-Type':'application/json',Authorization:`Bearer ${token}`};
 const refresh=async()=>{setLoading(true);try{const [a,s,i,q]=await Promise.all([fetch('/api/admin/aegis/dashboard',{headers,cache:'no-store'}),fetch('/api/admin/sales',{headers,cache:'no-store'}),fetch('/api/admin/inventory',{headers,cache:'no-store'}),fetch('/api/admin/approvals',{headers,cache:'no-store'})]);if(a.ok)setData(await a.json());if(s.ok)setSales(await s.json());if(i.ok){const x=await i.json();setInventory(x);setStockInput(String(x.physical_kg??''));}if(q.ok)setApprovals(await q.json());}catch{toast.error('Could not refresh Estate Tea AI');}finally{setLoading(false)}};useEffect(()=>{refresh()},[token]);
 const snap=data?.snapshot||{},attention=snap.attention||{},agents=snap.agents||[],inv=inventory||snap.inventory||{},activity=data?.recent_activity||[];const ordered=useMemo(()=>['Aegis','Scout','Brew','Steward','Ledger','Muse'].map(name=>agents.find(a=>a.agent===name)||{agent:name,status:name==='Muse'?'standby':'unknown',enabled:true}),[agents]);const current=ordered.find(a=>a.agent===selected)||ordered[0];
 const send=async()=>{const text=message.trim();if(!text)return;setSending(true);try{const r=await fetch('/api/admin/aegis/commands',{method:'POST',headers,body:JSON.stringify({message:text})});const b=await r.json();if(!r.ok)throw new Error(b.detail||b.error||'Command failed');setLastCommand(b);setMessage('');toast.success('Aegis received your instruction');refresh();}catch(e){toast.error(e.message||'Aegis command failed')}finally{setSending(false)}};
 const decide=async(item,decision)=>{const id=item.approval_id||item.id;if(!id)return toast.error('Approval ID is missing');setBusyApproval(id);try{const r=await fetch(`/api/admin/approvals/${encodeURIComponent(id)}`,{method:'PUT',headers,body:JSON.stringify({decision})});const b=await r.json();if(!r.ok)throw new Error(b.detail||b.error||'Decision failed');toast.success(decision==='approve'?'Approved for Brew':'Rejected');await refresh();}catch(e){toast.error(e.message||'Could not update approval')}finally{setBusyApproval(null)}};
 const saveStock=async()=>{setSavingStock(true);try{const r=await fetch('/api/admin/inventory',{method:'PUT',headers,body:JSON.stringify({physical_kg:Number(stockInput)})});const b=await r.json();if(!r.ok)throw new Error(b.detail||b.error);setInventory(b);toast.success('Inventory updated through Steward');refresh();}catch(e){toast.error(e.message||'Inventory update failed')}finally{setSavingStock(false)}};
 const agentActivity=activity.filter(x=>String(x.agent||x.source||'').toLowerCase()===selected.toLowerCase()).slice(0,5);const status=a=>a.enabled===false?'Paused':a.agent==='Muse'?'Retainer':(['online','active','running'].includes(String(a.status).toLowerCase())?'Active':(a.status||'No status reported'));
 if(loading&&!data)return <div className="py-16 text-center text-sm text-gray-500">Connecting to Aegis…</div>;
 return <div className="grid md:grid-cols-[150px_1fr] gap-5"><aside className="md:sticky md:top-24 md:self-start flex md:flex-col gap-1 overflow-x-auto">{[[Home,'home','Home'],[Users,'agents','Agents'],[BarChart3,'reports','Reports'],[Settings,'settings','Settings']].map(([Icon,id,label])=><button key={id} onClick={()=>setSection(id)} className={`flex items-center gap-2 px-3 py-3 rounded-xl text-xs whitespace-nowrap ${section===id?'bg-[#D4AF37]/10 text-[#D4AF37] border border-[#D4AF37]/25':'text-gray-500 hover:text-white'}`}><Icon className="w-4 h-4"/>{label}</button>)}</aside><div className="min-w-0 space-y-5"><div><h2 className="text-2xl sm:text-3xl font-light text-white">{greeting()}, welcome back.</h2><p className="text-xs text-gray-600 mt-1">Estate Tea AI is connected to live operations.</p></div>
 {section==='home'&&<>{approvals.count>=3&&<button onClick={()=>setReviewing(true)} className="w-full card-surface rounded-xl p-4 border border-[#D4AF37]/30 flex items-center justify-between text-left"><div><p className="text-sm text-white">{approvals.count} things waiting for approval</p><p className="text-xs text-gray-500 mt-1">Aegis has the next 3 ready.</p></div><ChevronRight className="w-4 h-4 text-[#D4AF37]"/></button>}<AgentStrip agents={ordered} selected={selected} setSelected={setSelected} status={status}/><AgentDetail agent={current} activity={agentActivity} detailTab={detailTab} setDetailTab={setDetailTab} status={status} onMessage={()=>{setSelected(current.agent);setSection('home');document.getElementById('aegis-message')?.focus()}}/><CommandBox message={message} setMessage={setMessage} send={send} sending={sending} lastCommand={lastCommand}/><div className="grid grid-cols-2 lg:grid-cols-4 gap-3"><Metric label="Website orders" value={sales?.website?.summary?.orders||0} icon={Globe2}/><Metric label="AI sales orders" value={sales?.ai_sales?.summary?.orders||0} icon={BriefcaseBusiness}/><Metric label="Open incidents" value={attention.open_incidents||0} icon={AlertTriangle}/><Metric label="Sellable kg" value={inv.sellable_kg??'—'} icon={Boxes}/></div></>}
 {section==='agents'&&<><AgentStrip agents={ordered} selected={selected} setSelected={setSelected} status={status}/><AgentDetail agent={current} activity={agentActivity} detailTab={detailTab} setDetailTab={setDetailTab} status={status} onMessage={()=>setSection('home')}/></>}
 {section==='reports'&&<><div className="flex gap-1 bg-white/5 p-1 rounded-xl overflow-x-auto">{[['website','Website Sales'],['ai','AI Sales'],['inventory','Inventory']].map(([id,l])=><button key={id} onClick={()=>setReport(id)} className={`flex-1 px-3 py-2 rounded-lg text-xs whitespace-nowrap ${report===id?'bg-[#D4AF37]/10 text-[#D4AF37]':'text-gray-500'}`}>{l}</button>)}</div>{report==='website'&&<SalesView title="Website Sales" data={sales?.website} icon={Globe2}/>} {report==='ai'&&<SalesView title="AI Sales" data={sales?.ai_sales} icon={BriefcaseBusiness}/>} {report==='inventory'&&<InventoryView inv={inv} stockInput={stockInput} setStockInput={setStockInput} saveStock={saveStock} saving={savingStock}/>}</>}
 {section==='settings'&&<div className="card-surface rounded-2xl border border-white/5 p-5"><p className="text-sm text-white">Owner controls</p><p className="text-xs text-gray-500 mt-2">PIN access is active. Agent-level controls and device passkey registration will live here.</p><div className="mt-5 grid sm:grid-cols-2 gap-3"><Info label="Approval batch" value="3 items"/><Info label="Brew customer sends" value="Owner approval required"/></div></div>}
 <button onClick={refresh} disabled={loading} className="flex items-center gap-2 text-xs text-gray-600 hover:text-[#D4AF37]"><RefreshCw className={`w-4 h-4 ${loading?'animate-spin':''}`}/>Refresh live data</button></div>{reviewing&&<ApprovalModal approvals={approvals} busy={busyApproval} decide={decide} close={()=>setReviewing(false)}/>}</div>;
}
function greeting(){const h=new Date().getHours();return h<12?'Good morning':h<17?'Good afternoon':'Good evening'}
function Avatar({name,big=false}){return <div className={`${big?'w-16 h-16 text-lg':'w-11 h-11 text-xs'} rounded-2xl bg-gradient-to-br from-[#D4AF37]/25 to-white/[.03] border border-[#D4AF37]/20 flex items-center justify-center text-[#D4AF37] font-medium`}>{META[name]?.[1]||name.slice(0,2)}</div>}
function AgentStrip({agents,selected,setSelected,status}){return <div className="grid grid-cols-2 sm:grid-cols-3 xl:grid-cols-6 gap-2">{agents.map(a=><button key={a.agent} onClick={()=>setSelected(a.agent)} className={`text-left rounded-2xl p-3 border transition-all duration-200 ${selected===a.agent?'bg-[#D4AF37]/10 border-[#D4AF37]/40 -translate-y-0.5':'bg-white/[.025] border-white/5 hover:border-white/15'}`}><Avatar name={a.agent}/><div className="mt-3 flex items-center gap-2"><p className="text-sm text-white">{a.agent}</p><span className={`w-1.5 h-1.5 rounded-full ${a.enabled!==false&&a.agent!=='Muse'?'bg-green-400':'bg-gray-600'}`}/></div><p className="text-[10px] text-gray-600 mt-1 line-clamp-1">{META[a.agent]?.[0]}</p><p className="text-[10px] text-gray-500 mt-2 line-clamp-1">{status(a)}</p></button>)}</div>}
function AgentDetail({agent,activity,detailTab,setDetailTab,status,onMessage}){return <div className="card-surface rounded-2xl border border-white/5 p-5 transition-all duration-300"><div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4"><div className="flex items-center gap-4"><Avatar name={agent.agent} big/><div><h3 className="text-xl text-white font-light">{agent.agent}</h3><p className="text-xs text-gray-500">{META[agent.agent]?.[0]}</p><p className="text-xs text-[#D4AF37] mt-1">{status(agent)}</p></div></div><button onClick={onMessage} className="flex items-center justify-center gap-2 border border-[#D4AF37]/30 text-[#D4AF37] rounded-xl px-4 py-2 text-xs"><MessageCircle className="w-4 h-4"/>Message {agent.agent}</button></div><div className="flex gap-4 mt-6 border-b border-white/5">{[['activity','Recent Activity'],['task','Current Task']].map(([id,l])=><button key={id} onClick={()=>setDetailTab(id)} className={`pb-3 text-xs ${detailTab===id?'text-[#D4AF37] border-b border-[#D4AF37]':'text-gray-600'}`}>{l}</button>)}</div><div className="pt-4 min-h-20">{detailTab==='activity'?(activity.length?activity.map((x,i)=><div key={i} className="py-2 border-b border-white/5 last:border-0"><p className="text-xs text-gray-300">{x.summary||x.event_type||'Activity recorded'}</p><p className="text-[10px] text-gray-700 mt-1">{x.created_at?new Date(x.created_at).toLocaleString('en-IN'):''}</p></div>):<p className="text-xs text-gray-600">No recent activity reported.</p>):<p className="text-xs text-gray-500">{agent.current_task||agent.task||'No active task reported.'}</p>}</div></div>}
function CommandBox({message,setMessage,send,sending,lastCommand}){return <div className="card-surface rounded-2xl p-4 border border-[#D4AF37]/15"><div className="flex items-center gap-2 mb-3"><Bot className="w-5 h-5 text-[#D4AF37]"/><p className="text-sm text-white">Talk to Aegis</p></div><div className="flex gap-2"><textarea id="aegis-message" value={message} onChange={e=>setMessage(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();send()}}} placeholder="Tell Aegis what you need…" className="flex-1 min-h-[76px] resize-none bg-white/5 border border-white/10 rounded-xl px-3 py-3 text-sm text-white focus:border-[#D4AF37]/50 focus:outline-none"/><button onClick={send} disabled={sending||!message.trim()} className="self-end bg-[#D4AF37] disabled:bg-gray-700 text-black rounded-xl p-3"><Send className="w-4 h-4"/></button></div>{lastCommand&&<div className="mt-3 rounded-lg bg-white/[.03] p-3"><span className="text-[10px] gold-text">{lastCommand.command_id}</span><p className="text-xs text-gray-300 mt-1">{lastCommand.result?.message||'Command recorded.'}</p></div>}</div>}
function ApprovalModal({approvals,busy,decide,close}){const batch=(approvals.items||[]).slice(0,3);return <div className="fixed inset-0 z-[100] bg-black/80 backdrop-blur-sm p-4 flex items-end sm:items-center justify-center" onClick={close}><div onClick={e=>e.stopPropagation()} className="w-full max-w-2xl max-h-[85vh] overflow-y-auto bg-[#111] border border-white/10 rounded-2xl p-5"><div className="flex justify-between mb-4"><div><p className="text-white">Aegis · Approval batch</p><p className="text-xs text-gray-500">Review up to three items.</p></div><button onClick={close}><X className="w-5 h-5 text-gray-500"/></button></div>{batch.map((item,i)=><ApprovalCard key={item.approval_id||i} item={item} busy={busy} decide={decide}/>)}</div></div>}
function ApprovalCard({item,busy,decide}){const id=item.approval_id||item.id,subject=item.subject||item.email_subject||item.action_type||'Brew approval',body=item.body||item.email_body||item.draft_body||item.message||'';return <div className="rounded-xl border border-white/10 p-4 bg-white/[.02] mb-3"><p className="text-sm text-white">{subject}</p><p className="text-xs text-gray-600 mt-1">{item.business_name||item.to_email||'Brew'}</p>{body&&<p className="text-sm text-gray-400 mt-3 whitespace-pre-wrap line-clamp-6">{body}</p>}<div className="flex gap-2 mt-4"><button disabled={busy===id} onClick={()=>decide(item,'approve')} className="flex-1 bg-[#D4AF37] text-black rounded-lg py-2 text-xs">Approve</button><button disabled={busy===id} onClick={()=>decide(item,'reject')} className="flex-1 border border-white/10 text-gray-300 rounded-lg py-2 text-xs">Reject</button></div></div>}
function Metric({label,value,icon:Icon}){return <div className="card-surface rounded-xl p-4 border border-white/5"><Icon className="w-4 h-4 text-[#D4AF37] mb-3"/><p className="text-2xl text-white font-light">{value}</p><p className="text-[11px] text-gray-500 mt-1">{label}</p></div>}
function SalesView({title,data,icon:Icon}){const s=data?.summary||{},rows=data?.orders||[];return <div className="space-y-4"><div className="grid grid-cols-2 lg:grid-cols-4 gap-3"><Metric label="Orders" value={s.orders||0} icon={Icon}/><Metric label="Paid" value={s.paid_orders||0} icon={CheckCircle2}/><Metric label="Revenue" value={`₹${Number(s.revenue||0).toLocaleString('en-IN')}`} icon={Icon}/><Metric label="Quantity / kg" value={s.items_or_kg||0} icon={PackageOpen}/></div><div className="card-surface rounded-xl border border-white/5 overflow-hidden"><div className="p-4 border-b border-white/5"><p className="text-sm text-white">{title}</p></div>{rows.slice(0,50).map((o,i)=><div key={o.order_id||o.id||i} className="p-4 border-b border-white/5 flex justify-between gap-3"><div><p className="text-sm text-gray-200">{o.business_name||o.customer_name||'Customer'}</p><p className="text-xs text-gray-600">{o.order_id||o.id||'—'} · {o.status||'recorded'}</p></div><p className="text-sm gold-text">₹{Number(o.total_amount||(Number(o.price||0)*Number(o.quantity||1))).toLocaleString('en-IN')}</p></div>)}{!rows.length&&<p className="p-4 text-sm text-gray-600">No {title.toLowerCase()} recorded yet.</p>}</div></div>}
function InventoryView({inv,stockInput,setStockInput,saveStock,saving}){return <div className="space-y-4"><div className="grid grid-cols-2 lg:grid-cols-4 gap-3"><Metric label="Physical kg" value={inv.physical_kg??'—'} icon={PackageOpen}/><Metric label="Committed kg" value={inv.committed_kg??'—'} icon={Clock3}/><Metric label="Sellable kg" value={inv.sellable_kg??'—'} icon={CheckCircle2}/><Metric label="Protected reserve" value={inv.protected_reserve_kg??2} icon={AlertTriangle}/></div><div className="card-surface rounded-xl p-4"><p className="text-sm text-white">Set physical stock</p><div className="flex gap-2 mt-4"><input type="number" min="0" step=".001" value={stockInput} onChange={e=>setStockInput(e.target.value)} className="w-40 bg-white/5 border border-white/10 rounded-xl px-3 py-2 text-white"/><button onClick={saveStock} disabled={saving} className="bg-[#D4AF37] text-black rounded-xl px-4 text-sm">{saving?'Saving…':'Update stock'}</button></div></div></div>}
function Info({label,value}){return <div className="rounded-xl bg-white/[.025] border border-white/5 p-4"><p className="text-[10px] text-gray-600 uppercase tracking-widest">{label}</p><p className="text-sm text-gray-300 mt-2">{value}</p></div>}
