'use client';
import { useEffect, useRef, useState } from 'react';
import { ArrowLeft, Lock, Smartphone, ScanFace } from 'lucide-react';
import { toast } from 'sonner';
import { startAuthentication, startRegistration, platformAuthenticatorIsAvailable } from '@simplewebauthn/browser';
import AIOpsPanel from './AIOpsPanel';

export default function AIOpsDashboard({ navigate }) {
  const [token,setToken]=useState(null),[pin,setPin]=useState(''),[logging,setLogging]=useState(false),[passkeyReady,setPasskeyReady]=useState(false),[statusLoaded,setStatusLoaded]=useState(false),[biometricBusy,setBiometricBusy]=useState(false),[offerEnrollment,setOfferEnrollment]=useState(false),[showPin,setShowPin]=useState(false);
  const autoUnlockStarted=useRef(false);

  const login=async()=>{if(!/^\d{6}$/.test(pin))return toast.error('Enter your six-digit PIN');setLogging(true);try{const r=await fetch('/api/admin/pin',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({pin})});const body=await r.json();if(!r.ok)throw new Error(body.error||'PIN failed');setToken(body.token);setPin('');if(!passkeyReady)setOfferEnrollment(true);toast.success('Estate Tea AI unlocked')}catch(e){toast.error(e.message||'Incorrect PIN')}finally{setLogging(false)}};

  const enrollFaceID=async()=>{if(!token)return;setBiometricBusy(true);try{const local=await platformAuthenticatorIsAvailable();if(!local)throw new Error('Face ID is not available on this device');const r=await fetch('/api/admin/passkey/register-options',{headers:{Authorization:`Bearer ${token}`},cache:'no-store'});const options=await r.json();if(!r.ok)throw new Error(options.error||'Could not start Face ID setup');const registration=await startRegistration({optionsJSON:options});const vr=await fetch('/api/admin/passkey/register-verify',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`},body:JSON.stringify(registration)});const result=await vr.json();if(!vr.ok||!result.verified)throw new Error(result.error||'Face ID setup failed');setPasskeyReady(true);setShowPin(false);setOfferEnrollment(false);toast.success('Face ID unlock is ready on this iPhone')}catch(e){if(e?.name!=='NotAllowedError')toast.error(e.message||'Face ID setup was cancelled')}finally{setBiometricBusy(false)}};

  const resetFaceID=async()=>{if(!token||biometricBusy)return;setBiometricBusy(true);try{const r=await fetch('/api/admin/passkey/reset',{method:'POST',headers:{Authorization:`Bearer ${token}`}});const result=await r.json();if(!r.ok)throw new Error(result.error||'Could not reset Face ID');setPasskeyReady(false);setBiometricBusy(false);toast.success('Old Face ID sign-in cleared. Create the new one now.');await enrollFaceID()}catch(e){setBiometricBusy(false);toast.error(e.message||'Could not reset Face ID')}};

  const unlockWithFaceID=async({quiet=false}={})=>{setBiometricBusy(true);setShowPin(false);try{const local=await platformAuthenticatorIsAvailable();if(!local)throw new Error('Face ID is not available on this device');const r=await fetch('/api/admin/passkey/auth-options',{cache:'no-store'});const options=await r.json();if(!r.ok)throw new Error(options.error||'Face ID is not enrolled');const authentication=await startAuthentication({optionsJSON:options});const vr=await fetch('/api/admin/passkey/auth-verify',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(authentication)});const result=await vr.json();if(!vr.ok||!result.verified||!result.token)throw new Error(result.error||'Face ID unlock failed');setToken(result.token);if(!quiet)toast.success('Unlocked with Face ID')}catch(e){setShowPin(true);if(!quiet&&e?.name!=='NotAllowedError')toast.error(e.message||'Face ID unlock failed')}finally{setBiometricBusy(false)}};

  useEffect(()=>{let alive=true;fetch('/api/admin/passkey/status',{cache:'no-store'}).then(r=>r.ok?r.json():null).then(async b=>{if(!alive)return;const enrolled=!!b?.enrolled;setPasskeyReady(enrolled);if(!enrolled){setShowPin(true);return}setShowPin(false);if(!autoUnlockStarted.current){autoUnlockStarted.current=true;await unlockWithFaceID({quiet:true})}}).catch(()=>{if(alive)setShowPin(true)}).finally(()=>{if(alive)setStatusLoaded(true)});return()=>{alive=false}},[]);

  if(!token)return <div className="min-h-screen bg-[#0a0a0a] flex items-center justify-center p-4"><div className="card-surface rounded-2xl p-6 sm:p-8 max-w-sm w-full border border-white/10"><div className="text-center mb-6"><div className="mx-auto w-14 h-14 rounded-full bg-[#D4AF37]/10 border border-[#D4AF37]/30 flex items-center justify-center mb-4">{passkeyReady?<ScanFace className="w-7 h-7 text-[#D4AF37]"/>:<Lock className="w-6 h-6 text-[#D4AF37]"/>}</div><h1 className="text-2xl font-light gold-text">Estate Tea AI</h1><p className="text-xs text-gray-500 mt-1">Private Owner Web App</p></div>{!statusLoaded||biometricBusy?<div className="py-5 text-center"><ScanFace className="w-7 h-7 text-[#D4AF37] mx-auto mb-3"/><p className="text-sm text-gray-400">{biometricBusy?'Unlocking with Face ID…':'Checking secure access…'}</p></div>:passkeyReady&&!showPin?<><button onClick={()=>unlockWithFaceID()} className="w-full bg-[#D4AF37] text-black font-medium py-3 rounded-xl text-sm flex items-center justify-center gap-2"><ScanFace className="w-5 h-5"/>Try Face ID again</button><button onClick={()=>setShowPin(true)} className="mt-4 w-full text-xs text-gray-600 hover:text-[#D4AF37]">Use PIN instead</button></>:<><input inputMode="numeric" autoComplete="one-time-code" maxLength={6} value={pin} onChange={e=>setPin(e.target.value.replace(/\D/g,'').slice(0,6))} onKeyDown={e=>e.key==='Enter'&&login()} placeholder="••••••" className="w-full bg-white/5 border border-white/10 rounded-xl px-4 py-4 text-center tracking-[0.6em] text-xl text-white placeholder-gray-600 focus:border-[#D4AF37]/50 focus:outline-none"/><button onClick={login} disabled={logging||pin.length!==6} className="mt-4 w-full bg-[#D4AF37] disabled:bg-gray-700 text-black font-medium py-3 rounded-xl text-sm">{logging?'Unlocking…':'Unlock with PIN'}</button>{passkeyReady&&<button onClick={()=>unlockWithFaceID()} className="mt-4 w-full text-xs text-gray-600 hover:text-[#D4AF37]">Try Face ID again</button>}</>}<div className="mt-5 flex items-start gap-2 text-[11px] text-gray-600"><Smartphone className="w-4 h-4 shrink-0"/><p>{passkeyReady?'Face ID starts automatically. PIN appears only if local Face ID is cancelled, unavailable, or fails.':'Unlock once with your PIN, then enable Face ID for future access.'}</p></div></div></div>;

  return <div className="min-h-screen bg-[#0a0a0a]"><header className="glass-surface border-b border-white/10 sticky top-0 z-50"><div className="max-w-6xl mx-auto px-4 py-3 flex items-center justify-between"><div className="flex items-center gap-3"><button onClick={()=>navigate('store')} className="text-gray-400 hover:text-white"><ArrowLeft className="w-5 h-5"/></button><div><h1 className="text-lg font-light gold-text">Estate Tea AI</h1><p className="text-[10px] text-gray-600">Owner Command Center</p></div></div><button onClick={()=>{autoUnlockStarted.current=false;setToken(null);setShowPin(false)}} className="text-xs text-gray-500 hover:text-red-400">Lock</button></div></header>{offerEnrollment&&<div className="max-w-6xl mx-auto px-4 pt-4"><div className="rounded-2xl border border-[#D4AF37]/30 bg-[#D4AF37]/5 p-4 flex flex-col sm:flex-row sm:items-center justify-between gap-3"><div className="flex gap-3"><ScanFace className="w-6 h-6 text-[#D4AF37] shrink-0"/><div><p className="text-sm text-white">Enable Face ID unlock</p><p className="text-xs text-gray-500 mt-1">Your iPhone handles the biometric check. Estate Tea never receives or stores your face data.</p></div></div><div className="flex gap-2"><button onClick={()=>setOfferEnrollment(false)} className="px-4 py-2 text-xs text-gray-500">Later</button><button onClick={enrollFaceID} disabled={biometricBusy} className="rounded-xl bg-[#D4AF37] text-black px-4 py-2 text-xs font-medium disabled:bg-gray-700">{biometricBusy?'Setting up…':'Enable Face ID'}</button></div></div></div>}<main className="max-w-6xl mx-auto px-4 py-6"><AIOpsPanel token={token} faceIDReady={passkeyReady} faceIDBusy={biometricBusy} onSetupFaceID={passkeyReady?resetFaceID:enrollFaceID}/></main></div>;
}
