import { verifyAdmin } from '@/lib/admin-auth';
const AEGIS_URL=(process.env.AEGIS_URL||'https://estate-tea-aegis.onrender.com').replace(/\/$/,'');
const line=(v='')=>String(v??'');
export async function GET(request,{params}){
 if(!verifyAdmin(request))return new Response('Unauthorized',{status:401});
 const {reportId}=await params;
 const r=await fetch(`${AEGIS_URL}/api/aegis/reports/daily`,{cache:'no-store'});
 const rows=await r.json().catch(()=>[]);
 const report=(Array.isArray(rows)?rows:[]).find(x=>x.report_id===reportId);
 if(!report)return new Response('Report not found',{status:404});
 const b=report.owner_brief||{},n=b.numbers||{},parts=[
  b.headline||'Estate Tea — Aegis report',
  'Report ID: '+line(report.report_id),
  'Created: '+line(report.created_at),'',
  'SUMMARY',line(b.plain_summary),'',
  'WHAT NEEDS YOU',...(b.what_needs_you||['Nothing needs your immediate attention.']).map(x=>'• '+line(x)),'',
  'TEAM TODAY',...(b.team_today||[]).map(x=>'• '+line(x)),'',
  'AT A GLANCE',
  'Pending approvals: '+line(n.pending_approvals??0),
  'Open issues: '+line(n.open_issues??0),
  'Pending handoffs: '+line(n.pending_handoffs??0),
  'Awaiting payment: '+line(n.awaiting_payment??0),'',
  'Generated by Aegis for Estate Tea.'
 ];
 return new Response(parts.join('\n'),{status:200,headers:{'Content-Type':'text/plain; charset=utf-8','Content-Disposition':`attachment; filename="Estate-Tea-Aegis-${reportId}.txt"`,'Cache-Control':'no-store'}});
}
